const terms = [
   "Affordable Housing",
   "Housing",
   "Market Housing",
   "Homeless shelters",
   "Transitional Housing",
   "Social Housing",
   "Subsidized Housing",
   "Non-Market Housing",
   "rent",
   "rent control",
   "house",
   "apartment",
   "lease",
   "mortgage",
   "Low-income housing",
   "Housing assistance",
   "Housing subsidies",
   "Habitat for Humanity",
   "Public housing",
   "Housing vouchers",
   "Affordable housing developers",
   "Community land trusts",
   "Inclusionary zoning",
   "Fair housing laws",
   "Affordable housing lotteries",
   "Affordable housing preservation",
   "Housing co-operatives",
   "Transitional housing",
   "Homeownership assistance",
   "Affordable housing tax credits",
   "Housing trust funds",
   "Homelessness",
   "Shelter",
   "Eviction",
   "Gentrification",
   "Housing crisis",
   "Cost-burdened",
   "Subsidized housing",
   "Homeownership counseling",
   "Rental assistance",
   "Tenant rights",
   "Homeownership programs",
   "Affordable mortgage programs",
   "Low-income tax credits",
   "Down payment assistance",
   "Affordable senior housing",
   "Fair market rent",
   "Energy-efficient housing",
   "Universal design",
   "Green building",
   "Mixed-income housing",
   "Redevelopment",
   "Infill development",
   "Density bonuses",
   "Micro-housing",
   "Manufactured housing",
   "Co-housing",
   "Tiny homes",
   "Shared equity homeownership",
   "Land banking",
];

module.exports.terms = terms;
