# The Deployment spec is very much similar to the one we created in the frontend deployment
# except that we are using a different image.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightly-staging-backend # TODO: Change the name to your application name with a backend suffix
  namespace: insightly-staging # TODO: Change the namespace to your application name with a production suffix

spec:
  replicas: 1
  selector:
    matchLabels:
      # TODO: Change the app label to your application name with a backend suffix
      # Must match the app label in the template field.
      app: insightly-backend
  template:
    metadata:
      labels:
        # TODO: Change the app label to your application name with a backend suffix
        # Must match the app label in the selector field above.
        app: insightly-backend
    spec:
      containers:
        - name: insightly # TODO: replace this with your application name
          resources: {}
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: insightly-secrets
                  key: mongo-initdb-root-username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insightly-secrets
                  key: mongo-initdb-root-password

            - name: MONGO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: insightly-configmap
                  key: mongo-host-for-backend
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: insightly-configmap
                  key: mongo-port-for-backend

            - name: MONGO_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: insightly-configmap
                  key: mongo-initdb-database

          ports:
            - containerPort: 8080
          image: registry.socs.uoguelph.ca/3760w23/t1/insightly/cis3760project/backend:staging
          imagePullPolicy: Always # Comment out this line if you are running locally

          # image: three-container-be:latest # TODO: replace this with your local image name to run locally or comment it out to run from the registry
          # imagePullPolicy: Never # Comment out the imagePullPolicy field if you are NOT running locally. Otherwise, set it to Never.

      imagePullSecrets:
        - name: regcred # TODO: replace this with your image pull secret name

# Trigger the deployment
