apiVersion: v1
kind: ConfigMap
metadata:
  name: insightly-configmap
  namespace: insightly-staging
data:
  # https://stackoverflow.com/questions/49129809/kubernetes-how-to-send-data-from-a-pod-to-another-pod-in-kubernetes
  react-app-server-base: http://insightly-staging-backend-service.insightly-staging
  react-app-server-port: "8080"
  mongo-initdb-database: task-management
  mongo-port-for-backend: "27017"
  mongo-host-for-backend: insightly-staging-mongo-service.insightly-staging
# Trigger the deployment
