apiVersion: v1
kind: Secret
metadata:
  name: insightly-secrets
  namespace: insightly-staging
type: Opaque
# echo -n "root" | base64
# echo -n "example" | base64
data:
  mongo-initdb-root-password: ZXhhbXBsZQ==
  mongo-initdb-root-username: cm9vdA==
# Trigger the deployment
